# Script to analyze AI-generated code contributions
# This script analyzes git history to identify code generated by Cursor/AI

param(
    [string]$OutputFile = "ai-code-report.md",
    [switch]$Detailed = $false
)

Write-Host "Analyzing Git History for AI-Generated Code..." -ForegroundColor Cyan

# Check if git is available
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Host "Error: Git is not installed or not in PATH" -ForegroundColor Red
    exit 1
}

# Check if we're in a git repository
if (-not (Test-Path .git)) {
    Write-Host "Error: Not a git repository. Please initialize git first." -ForegroundColor Red
    exit 1
}

# Keywords that might indicate AI-generated code
$aiKeywords = @(
    "cursor", "ai", "assistant", "generated", "composer", 
    "copilot", "chatgpt", "claude", "gpt", "llm",
    "auto-generated", "ai-assisted", "codegen"
)

# Get all commits
Write-Host "Fetching commit history..." -ForegroundColor Yellow
$commits = git log --all --pretty=format:"%H|%an|%ae|%ad|%s" --date=iso

if (-not $commits) {
    Write-Host "No commits found." -ForegroundColor Yellow
    exit 0
}

$aiCommits = @()
$totalCommits = 0
$totalFilesChanged = 0
$aiFilesChanged = 0
$totalLinesAdded = 0
$aiLinesAdded = 0
$totalLinesDeleted = 0
$aiLinesDeleted = 0

# Analyze each commit
foreach ($commitLine in $commits) {
    $totalCommits++
    $parts = $commitLine -split '\|'
    if ($parts.Length -lt 5) { continue }
    
    $hash = $parts[0]
    $author = $parts[1]
    $email = $parts[2]
    $date = $parts[3]
    $message = $parts[4]
    
    # Check if commit message contains AI keywords
    $isAICommit = $false
    $matchedKeywords = @()
    
    foreach ($keyword in $aiKeywords) {
        if ($message -match $keyword -or $author -match $keyword -or $email -match $keyword) {
            $isAICommit = $true
            $matchedKeywords += $keyword
        }
    }
    
    if ($isAICommit) {
        # Get stats for this commit
        $stats = git show --stat --format="" $hash 2>$null
        $filesChanged = 0
        $linesAdded = 0
        $linesDeleted = 0
        
        if ($stats) {
            # Parse stats: "X files changed, Y insertions(+), Z deletions(-)"
            if ($stats -match '(\d+)\s+files?\s+changed') {
                $filesChanged = [int]$Matches[1]
            }
            if ($stats -match '(\d+)\s+insertions?') {
                $linesAdded = [int]$Matches[1]
            }
            if ($stats -match '(\d+)\s+deletions?') {
                $linesDeleted = [int]$Matches[1]
            }
        }
        
        $aiCommits += [PSCustomObject]@{
            Hash = $hash.Substring(0, 8)
            FullHash = $hash
            Author = $author
            Email = $email
            Date = $date
            Message = $message
            Keywords = $matchedKeywords -join ", "
            FilesChanged = $filesChanged
            LinesAdded = $linesAdded
            LinesDeleted = $linesDeleted
        }
        
        $aiFilesChanged += $filesChanged
        $aiLinesAdded += $linesAdded
        $aiLinesDeleted += $linesDeleted
    }
    
    # Get total stats
    $commitStats = git show --stat --format="" $hash 2>$null
    if ($commitStats) {
        if ($commitStats -match '(\d+)\s+files?\s+changed') {
            $totalFilesChanged += [int]$Matches[1]
        }
        if ($commitStats -match '(\d+)\s+insertions?') {
            $totalLinesAdded += [int]$Matches[1]
        }
        if ($commitStats -match '(\d+)\s+deletions?') {
            $totalLinesDeleted += [int]$Matches[1]
        }
    }
}

# Generate report
$report = @"
# AI-Generated Code Analysis Report

**Generated:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")  
**Repository:** $(git rev-parse --show-toplevel)

---

## Summary

- **Total Commits Analyzed:** $totalCommits
- **AI-Related Commits:** $($aiCommits.Count)
- **AI Code Percentage:** $([math]::Round(($aiCommits.Count / $totalCommits) * 100, 2))%

### Code Statistics

| Metric | Total | AI-Generated | Percentage |
|--------|-------|--------------|------------|
| Commits | $totalCommits | $($aiCommits.Count) | $([math]::Round(($aiCommits.Count / $totalCommits) * 100, 2))% |
| Files Changed | $totalFilesChanged | $aiFilesChanged | $([math]::Round(($aiFilesChanged / [Math]::Max($totalFilesChanged, 1)) * 100, 2))% |
| Lines Added | $totalLinesAdded | $aiLinesAdded | $([math]::Round(($aiLinesAdded / [Math]::Max($totalLinesAdded, 1)) * 100, 2))% |
| Lines Deleted | $totalLinesDeleted | $aiLinesDeleted | $([math]::Round(($aiLinesDeleted / [Math]::Max($totalLinesDeleted, 1)) * 100, 2))% |

---

## AI-Related Commits

"@

if ($aiCommits.Count -eq 0) {
    $report += [Environment]::NewLine + "*No commits found matching AI-related keywords.*" + [Environment]::NewLine + [Environment]::NewLine
    $report += "**Note:** This script identifies AI-generated code by searching commit messages, author names, and email addresses for keywords like: ``cursor``, ``ai``, ``assistant``, ``generated``, etc." + [Environment]::NewLine + [Environment]::NewLine
    $report += "To improve tracking, consider:" + [Environment]::NewLine
    $report += "- Adding ``[AI]`` or ``[Cursor]`` prefix to commit messages for AI-generated code" + [Environment]::NewLine
    $report += "- Using a consistent commit message format" + [Environment]::NewLine
    $report += "- Adding code comments like ``// Generated by Cursor`` or ``<!-- AI-assisted -->``"
} else {
    $report += [Environment]::NewLine + "| Hash | Author | Date | Message | Files | Lines +/- | Keywords |" + [Environment]::NewLine
    $report += "|------|--------|------|---------|-------|-----------|----------|" + [Environment]::NewLine
    
    foreach ($commit in $aiCommits) {
        $linesChange = "+$($commit.LinesAdded) / -$($commit.LinesDeleted)"
        $message = $commit.Message -replace '\|', '&#124;' -replace '\n', ' '  # Escape markdown
        if ($message.Length -gt 60) {
            $message = $message.Substring(0, 57) + "..."
        }
        $remoteUrl = git config --get remote.origin.url 2>$null
        if ($remoteUrl) {
            $remoteUrl = $remoteUrl -replace '\.git$', ''
            $commitLink = "[$($commit.Hash)]($remoteUrl/commit/$($commit.FullHash))"
        } else {
            $commitLink = $commit.Hash.Substring(0, 8)
        }
        $report += "| $commitLink | $($commit.Author) | $($commit.Date.Split(' ')[0]) | $message | $($commit.FilesChanged) | $linesChange | $($commit.Keywords) |" + [Environment]::NewLine
    }
    
    if ($Detailed) {
        $report += [Environment]::NewLine + "---" + [Environment]::NewLine + [Environment]::NewLine + "## Detailed Commit Information" + [Environment]::NewLine + [Environment]::NewLine
        foreach ($commit in $aiCommits) {
            $report += "### Commit: $($commit.Hash)" + [Environment]::NewLine + [Environment]::NewLine
            $report += "- **Author:** $($commit.Author) <$($commit.Email)>" + [Environment]::NewLine
            $report += "- **Date:** $($commit.Date)" + [Environment]::NewLine
            $report += "- **Message:** $($commit.Message)" + [Environment]::NewLine
            $report += "- **Files Changed:** $($commit.FilesChanged)" + [Environment]::NewLine
            $report += "- **Lines Added:** $($commit.LinesAdded)" + [Environment]::NewLine
            $report += "- **Lines Deleted:** $($commit.LinesDeleted)" + [Environment]::NewLine
            $report += "- **Matched Keywords:** $($commit.Keywords)" + [Environment]::NewLine + [Environment]::NewLine
            
            # Get file list for this commit
            $files = git diff-tree --no-commit-id --name-only -r $commit.FullHash
            if ($files) {
                $report += "**Files Modified:**" + [Environment]::NewLine
                foreach ($file in $files) {
                    $report += "- ``$file``" + [Environment]::NewLine
                }
                $report += [Environment]::NewLine
            }
        }
    }
}

$report += @"

---

## Recommendations

1. **Standardize Commit Messages:** Use prefixes like `[AI]` or `[Cursor]` for AI-generated code
2. **Add Code Comments:** Include `// Generated by Cursor` or similar comments in AI-generated code
3. **Track Separately:** Consider using git tags or branches for AI-generated features
4. **Regular Reports:** Run this script periodically to track AI code percentage over time

---

## How to Improve Tracking

To get more accurate results, consider:

1. **Commit Message Convention:**
   ```
   [AI] Add medicine catalog feature
   [Cursor] Implement shopping cart service
   ```

2. **Code Comments:**
   ```typescript
   // Generated by Cursor AI Assistant
   // This component was created with AI assistance
   ```

3. **Git Hooks:** Add a pre-commit hook to prompt for AI usage
4. **Branch Naming:** Use branches like `feature/ai-catalog-service`

---

*Report generated by analyze-ai-code.ps1*
"@

# Write report to file
$report | Out-File -FilePath $OutputFile -Encoding UTF8
Write-Host ""
Write-Host "Report generated: $OutputFile" -ForegroundColor Green
Write-Host ""
Write-Host "Summary:" -ForegroundColor Cyan
Write-Host "  Total Commits: $totalCommits"
Write-Host "  AI-Related Commits: $($aiCommits.Count)"
Write-Host "  AI Code Percentage: $([math]::Round(($aiCommits.Count / $totalCommits) * 100, 2))%"

if ($aiCommits.Count -gt 0) {
    Write-Host ""
    Write-Host "Top AI Contributors:" -ForegroundColor Cyan
    $aiCommits | Group-Object Author | Sort-Object Count -Descending | Select-Object -First 5 | ForEach-Object {
        Write-Host "  $($_.Name): $($_.Count) commits"
    }
}

