#!/bin/bash
# Script to analyze AI-generated code contributions
# This script analyzes git history to identify code generated by Cursor/AI

OUTPUT_FILE="${1:-ai-code-report.md}"
DETAILED="${2:-false}"

echo "Analyzing Git History for AI-Generated Code..."

# Check if git is available
if ! command -v git &> /dev/null; then
    echo "Error: Git is not installed or not in PATH"
    exit 1
fi

# Check if we're in a git repository
if [ ! -d .git ]; then
    echo "Error: Not a git repository. Please initialize git first."
    exit 1
fi

# Keywords that might indicate AI-generated code
AI_KEYWORDS=("cursor" "ai" "assistant" "generated" "composer" "copilot" "chatgpt" "claude" "gpt" "llm" "auto-generated" "ai-assisted" "codegen")

# Get all commits
echo "Fetching commit history..."
COMMITS=$(git log --all --pretty=format:"%H|%an|%ae|%ad|%s" --date=iso)

if [ -z "$COMMITS" ]; then
    echo "No commits found."
    exit 0
fi

# Initialize counters
TOTAL_COMMITS=0
AI_COMMITS_COUNT=0
TOTAL_FILES=0
AI_FILES=0
TOTAL_LINES_ADDED=0
AI_LINES_ADDED=0
TOTAL_LINES_DELETED=0
AI_LINES_DELETED=0

# Temporary file for AI commits
TEMP_FILE=$(mktemp)
trap "rm -f $TEMP_FILE" EXIT

# Analyze each commit
while IFS= read -r commit_line; do
    TOTAL_COMMITS=$((TOTAL_COMMITS + 1))
    
    IFS='|' read -r hash author email date message <<< "$commit_line"
    
    # Check if commit message contains AI keywords
    IS_AI_COMMIT=false
    MATCHED_KEYWORDS=""
    
    for keyword in "${AI_KEYWORDS[@]}"; do
        if echo "$message $author $email" | grep -qi "$keyword"; then
            IS_AI_COMMIT=true
            if [ -z "$MATCHED_KEYWORDS" ]; then
                MATCHED_KEYWORDS="$keyword"
            else
                MATCHED_KEYWORDS="$MATCHED_KEYWORDS, $keyword"
            fi
        fi
    done
    
    if [ "$IS_AI_COMMIT" = true ]; then
        AI_COMMITS_COUNT=$((AI_COMMITS_COUNT + 1))
        
        # Get stats for this commit
        STATS=$(git show --stat --format="" "$hash" 2>/dev/null)
        FILES_CHANGED=0
        LINES_ADDED=0
        LINES_DELETED=0
        
        if [ -n "$STATS" ]; then
            FILES_CHANGED=$(echo "$STATS" | grep -oE '[0-9]+ files? changed' | grep -oE '[0-9]+' | head -1)
            LINES_ADDED=$(echo "$STATS" | grep -oE '[0-9]+ insertions?' | grep -oE '[0-9]+' | head -1)
            LINES_DELETED=$(echo "$STATS" | grep -oE '[0-9]+ deletions?' | grep -oE '[0-9]+' | head -1)
            
            FILES_CHANGED=${FILES_CHANGED:-0}
            LINES_ADDED=${LINES_ADDED:-0}
            LINES_DELETED=${LINES_DELETED:-0}
        fi
        
        AI_FILES=$((AI_FILES + FILES_CHANGED))
        AI_LINES_ADDED=$((AI_LINES_ADDED + LINES_ADDED))
        AI_LINES_DELETED=$((AI_LINES_DELETED + LINES_DELETED))
        
        # Store commit info
        echo "$hash|$author|$email|$date|$message|$MATCHED_KEYWORDS|$FILES_CHANGED|$LINES_ADDED|$LINES_DELETED" >> "$TEMP_FILE"
    fi
    
    # Get total stats
    STATS=$(git show --stat --format="" "$hash" 2>/dev/null)
    if [ -n "$STATS" ]; then
        FILES=$(echo "$STATS" | grep -oE '[0-9]+ files? changed' | grep -oE '[0-9]+' | head -1)
        ADDED=$(echo "$STATS" | grep -oE '[0-9]+ insertions?' | grep -oE '[0-9]+' | head -1)
        DELETED=$(echo "$STATS" | grep -oE '[0-9]+ deletions?' | grep -oE '[0-9]+' | head -1)
        
        TOTAL_FILES=$((TOTAL_FILES + ${FILES:-0}))
        TOTAL_LINES_ADDED=$((TOTAL_LINES_ADDED + ${ADDED:-0}))
        TOTAL_LINES_DELETED=$((TOTAL_LINES_DELETED + ${DELETED:-0}))
    fi
done <<< "$COMMITS"

# Calculate percentages
if [ $TOTAL_COMMITS -gt 0 ]; then
    COMMIT_PCT=$(awk "BEGIN {printf \"%.2f\", ($AI_COMMITS_COUNT / $TOTAL_COMMITS) * 100}")
else
    COMMIT_PCT=0
fi

if [ $TOTAL_FILES -gt 0 ]; then
    FILES_PCT=$(awk "BEGIN {printf \"%.2f\", ($AI_FILES / $TOTAL_FILES) * 100}")
else
    FILES_PCT=0
fi

if [ $TOTAL_LINES_ADDED -gt 0 ]; then
    LINES_ADDED_PCT=$(awk "BEGIN {printf \"%.2f\", ($AI_LINES_ADDED / $TOTAL_LINES_ADDED) * 100}")
else
    LINES_ADDED_PCT=0
fi

if [ $TOTAL_LINES_DELETED -gt 0 ]; then
    LINES_DELETED_PCT=$(awk "BEGIN {printf \"%.2f\", ($AI_LINES_DELETED / $TOTAL_LINES_DELETED) * 100}")
else
    LINES_DELETED_PCT=0
fi

# Generate report
REPO_ROOT=$(git rev-parse --show-toplevel)
CURRENT_DATE=$(date '+%Y-%m-%d %H:%M:%S')

cat > "$OUTPUT_FILE" << EOF
# AI-Generated Code Analysis Report

**Generated:** $CURRENT_DATE  
**Repository:** $REPO_ROOT

---

## Summary

- **Total Commits Analyzed:** $TOTAL_COMMITS
- **AI-Related Commits:** $AI_COMMITS_COUNT
- **AI Code Percentage:** $COMMIT_PCT%

### Code Statistics

| Metric | Total | AI-Generated | Percentage |
|--------|-------|--------------|------------|
| Commits | $TOTAL_COMMITS | $AI_COMMITS_COUNT | $COMMIT_PCT% |
| Files Changed | $TOTAL_FILES | $AI_FILES | $FILES_PCT% |
| Lines Added | $TOTAL_LINES_ADDED | $AI_LINES_ADDED | $LINES_ADDED_PCT% |
| Lines Deleted | $TOTAL_LINES_DELETED | $AI_LINES_DELETED | $LINES_DELETED_PCT% |

---

## AI-Related Commits

EOF

if [ $AI_COMMITS_COUNT -eq 0 ]; then
    cat >> "$OUTPUT_FILE" << EOF
*No commits found matching AI-related keywords.*

**Note:** This script identifies AI-generated code by searching commit messages, author names, and email addresses for keywords like: \`cursor\`, \`ai\`, \`assistant\`, \`generated\`, etc.

To improve tracking, consider:
- Adding \`[AI]\` or \`[Cursor]\` prefix to commit messages for AI-generated code
- Using a consistent commit message format
- Adding code comments like \`// Generated by Cursor\` or \`<!-- AI-assisted -->\`

EOF
else
    cat >> "$OUTPUT_FILE" << EOF
| Hash | Author | Date | Message | Files | Lines +/- | Keywords |
|------|--------|------|---------|-------|-----------|----------|
EOF
    
    while IFS='|' read -r hash author email date message keywords files added deleted; do
        SHORT_HASH=$(echo "$hash" | cut -c1-8)
        SHORT_DATE=$(echo "$date" | cut -d' ' -f1)
        LINES_CHANGE="+$added / -$deleted"
        
        # Truncate long messages
        if [ ${#message} -gt 60 ]; then
            message="${message:0:57}..."
        fi
        
        # Escape markdown
        message=$(echo "$message" | sed 's/|/\\|/g')
        
        echo "| $SHORT_HASH | $author | $SHORT_DATE | $message | $files | $LINES_CHANGE | $keywords |" >> "$OUTPUT_FILE"
    done < "$TEMP_FILE"
fi

cat >> "$OUTPUT_FILE" << EOF

---

## Recommendations

1. **Standardize Commit Messages:** Use prefixes like \`[AI]\` or \`[Cursor]\` for AI-generated code
2. **Add Code Comments:** Include \`// Generated by Cursor\` or similar comments in AI-generated code
3. **Track Separately:** Consider using git tags or branches for AI-generated features
4. **Regular Reports:** Run this script periodically to track AI code percentage over time

---

## How to Improve Tracking

To get more accurate results, consider:

1. **Commit Message Convention:**
   \`\`\`
   [AI] Add medicine catalog feature
   [Cursor] Implement shopping cart service
   \`\`\`

2. **Code Comments:**
   \`\`\`typescript
   // Generated by Cursor AI Assistant
   // This component was created with AI assistance
   \`\`\`

3. **Git Hooks:** Add a pre-commit hook to prompt for AI usage
4. **Branch Naming:** Use branches like \`feature/ai-catalog-service\`

---

*Report generated by analyze-ai-code.sh*
EOF

echo ""
echo "Report generated: $OUTPUT_FILE"
echo ""
echo "Summary:"
echo "  Total Commits: $TOTAL_COMMITS"
echo "  AI-Related Commits: $AI_COMMITS_COUNT"
echo "  AI Code Percentage: $COMMIT_PCT%"

if [ $AI_COMMITS_COUNT -gt 0 ]; then
    echo ""
    echo "Top AI Contributors:"
    cut -d'|' -f2 "$TEMP_FILE" | sort | uniq -c | sort -rn | head -5 | while read count author; do
        echo "  $author: $count commits"
    done
fi

